#!/usr/bin/env php
<?php

if (!file_exists(__DIR__.'/vendor/symfony/phpunit-bridge/bin/simple-phpunit')) {
    echo "Unable to find the `simple-phpunit` script in `vendor/symfony/phpunit-bridge/bin/`.\nPlease run `composer update` before running this command.\n";
    exit(1);
}

if (PHP_VERSION_ID >= 70000 && !getenv('GEOCODER_PHPUNIT_VERSION')) {
    putenv('GEOCODER_PHPUNIT_VERSION=6.0');
}

putenv('GEOCODER_PHPUNIT_DIR='.__DIR__.'/.phpunit');
require __DIR__.'/vendor/symfony/phpunit-bridge/bin/simple-phpunit';
